# this docker use for hosted your  nodejs app in container
# just add your service name  to add service to managed in this tools
# author Gerald Halomoan Samosir

version: '3'
services:
  test-project:
    container_name: testProject
    hostname: testProject
    image: test-project-app
    build: .
    network_mode: bridge
    volumes:
      - ./ProjectList/testProject:/App
    working_dir: /App
    command: npm start  
    ports:
      # {host port} : {container port}
      - 2000:3000
    tty: true
